# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 460)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.guitar = QtWidgets.QLabel(self.centralwidget)
        self.guitar.setObjectName("guitar")
        self.verticalLayout.addWidget(self.guitar)
        self.Eg = QtWidgets.QPushButton(self.centralwidget)
        self.Eg.setObjectName("Eg")
        self.verticalLayout.addWidget(self.Eg)
        self.Bg = QtWidgets.QPushButton(self.centralwidget)
        self.Bg.setObjectName("Bg")
        self.verticalLayout.addWidget(self.Bg)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.Gg = QtWidgets.QPushButton(self.centralwidget)
        self.Gg.setObjectName("Gg")
        self.verticalLayout_3.addWidget(self.Gg)
        self.Dg = QtWidgets.QPushButton(self.centralwidget)
        self.Dg.setObjectName("Dg")
        self.verticalLayout_3.addWidget(self.Dg)
        self.Ag = QtWidgets.QPushButton(self.centralwidget)
        self.Ag.setObjectName("Ag")
        self.verticalLayout_3.addWidget(self.Ag)
        self.Eg_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Eg_2.setObjectName("Eg_2")
        self.verticalLayout_3.addWidget(self.Eg_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.piano = QtWidgets.QLabel(self.centralwidget)
        self.piano.setObjectName("piano")
        self.verticalLayout_2.addWidget(self.piano)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.C = QtWidgets.QPushButton(self.centralwidget)
        self.C.setObjectName("C")
        self.horizontalLayout.addWidget(self.C)
        self.D = QtWidgets.QPushButton(self.centralwidget)
        self.D.setObjectName("D")
        self.horizontalLayout.addWidget(self.D)
        self.E = QtWidgets.QPushButton(self.centralwidget)
        self.E.setObjectName("E")
        self.horizontalLayout.addWidget(self.E)
        self.F = QtWidgets.QPushButton(self.centralwidget)
        self.F.setObjectName("F")
        self.horizontalLayout.addWidget(self.F)
        self.G = QtWidgets.QPushButton(self.centralwidget)
        self.G.setObjectName("G")
        self.horizontalLayout.addWidget(self.G)
        self.A = QtWidgets.QPushButton(self.centralwidget)
        self.A.setObjectName("A")
        self.horizontalLayout.addWidget(self.A)
        self.B = QtWidgets.QPushButton(self.centralwidget)
        self.B.setObjectName("B")
        self.horizontalLayout.addWidget(self.B)
        self.C1 = QtWidgets.QPushButton(self.centralwidget)
        self.C1.setObjectName("C1")
        self.horizontalLayout.addWidget(self.C1)
        self.D1 = QtWidgets.QPushButton(self.centralwidget)
        self.D1.setObjectName("D1")
        self.horizontalLayout.addWidget(self.D1)
        self.E1 = QtWidgets.QPushButton(self.centralwidget)
        self.E1.setObjectName("E1")
        self.horizontalLayout.addWidget(self.E1)
        self.F1 = QtWidgets.QPushButton(self.centralwidget)
        self.F1.setObjectName("F1")
        self.horizontalLayout.addWidget(self.F1)
        self.G1 = QtWidgets.QPushButton(self.centralwidget)
        self.G1.setObjectName("G1")
        self.horizontalLayout.addWidget(self.G1)
        self.A1 = QtWidgets.QPushButton(self.centralwidget)
        self.A1.setObjectName("A1")
        self.horizontalLayout.addWidget(self.A1)
        self.B1 = QtWidgets.QPushButton(self.centralwidget)
        self.B1.setObjectName("B1")
        self.horizontalLayout.addWidget(self.B1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1220, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.guitar.setText(_translate("MainWindow", "Guitar"))
        self.Eg.setText(_translate("MainWindow", "E"))
        self.Eg.setShortcut(_translate("MainWindow", "E"))
        self.Bg.setText(_translate("MainWindow", "B"))
        self.Bg.setShortcut(_translate("MainWindow", "B"))
        self.Gg.setText(_translate("MainWindow", "G"))
        self.Gg.setShortcut(_translate("MainWindow", "G"))
        self.Dg.setText(_translate("MainWindow", "D"))
        self.Dg.setShortcut(_translate("MainWindow", "D"))
        self.Ag.setText(_translate("MainWindow", "A"))
        self.Ag.setShortcut(_translate("MainWindow", "A"))
        self.Eg_2.setText(_translate("MainWindow", "E"))
        self.Eg_2.setShortcut(_translate("MainWindow", "Space"))
        self.piano.setText(_translate("MainWindow", "Piano"))
        self.C.setText(_translate("MainWindow", "C"))
        self.C.setShortcut(_translate("MainWindow", "1"))
        self.D.setText(_translate("MainWindow", "D"))
        self.D.setShortcut(_translate("MainWindow", "2"))
        self.E.setText(_translate("MainWindow", "E"))
        self.E.setShortcut(_translate("MainWindow", "3"))
        self.F.setText(_translate("MainWindow", "F"))
        self.F.setShortcut(_translate("MainWindow", "4"))
        self.G.setText(_translate("MainWindow", "G"))
        self.G.setShortcut(_translate("MainWindow", "5"))
        self.A.setText(_translate("MainWindow", "A"))
        self.A.setShortcut(_translate("MainWindow", "6"))
        self.B.setText(_translate("MainWindow", "B"))
        self.B.setShortcut(_translate("MainWindow", "7"))
        self.C1.setText(_translate("MainWindow", "C1"))
        self.C1.setShortcut(_translate("MainWindow", "8"))
        self.D1.setText(_translate("MainWindow", "D1"))
        self.D1.setShortcut(_translate("MainWindow", "9"))
        self.E1.setText(_translate("MainWindow", "E1"))
        self.E1.setShortcut(_translate("MainWindow", "0"))
        self.F1.setText(_translate("MainWindow", "F1"))
        self.F1.setShortcut(_translate("MainWindow", "-"))
        self.G1.setText(_translate("MainWindow", "G1"))
        self.G1.setShortcut(_translate("MainWindow", "="))
        self.A1.setText(_translate("MainWindow", "A1"))
        self.A1.setShortcut(_translate("MainWindow", "Backspace"))
        self.B1.setText(_translate("MainWindow", "B1"))
        self.B1.setShortcut(_translate("MainWindow", "NumLock"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

